### ISSUE TITLE
Fix navigation to different pages.

### ISSUE THREAD

**Issue by msecret** [18F/cg-landing#11]
I think to fix the issue where you can't get back from a different page, we should make the links in the headers not anchor links. This will break the functionality where it smooth scrolls back to the top, but ensures you can navigate correctly.

```
<a class="navbar-brand page-scroll" href="#page-top">
```

to

```
<a class="navbar-brand page-scroll" href="/">
```

**Comment by mogul** [comment]
Refers to long-gone version. But thanks, and sorry I took so long to respond!
