### ISSUE TITLE
Migrate old updates from docs.cloud.gov to cloud.gov/updates

### ISSUE THREAD

**Issue by afeld** [18F/cg-landing#18]
We should either make them visible again, or delete the [`_posts/`](https://github.com/18F/cf-landing/tree/master/_posts) directory.

**Comment by afeld** [comment]
- [ ] Combine with the Updates section of https://docs.18f.gov

**Comment by mogul** [comment]
> We should either make them visible again, or delete the _posts/ directory.

Already addressed, now visible at [the Updates page](https://cloud.gov/updates/).

> - [ ] Combine with the Updates section of https://docs.18f.gov

Still needed, PRs welcome.

**Comment by afeld** [comment]
Any preference on whether the updates live here or on the docs site? I'd lean slightly to the former.

**Comment by mogul** [comment]
I agree... I see these as updates about the capabilities of the product,
rather than documentation. I would like them to appear on cg-landing, with
pointers to correct pages in the docs for further information whenever
needed.
