### ISSUE TITLE
list pricing

### ISSUE THREAD

**Issue by afeld** [18F/cg-landing#20]
We get this question internally and externally _all the time_...would be good to have somewhere to point people to.

**Comment by wslack** [comment]
We get this question across business lines and I'd like to have a coordinated way to discuss it, fwiw.

**Comment by afeld** [comment]
Related Trello cards:
- https://trello.com/c/EsE2edi0/287-publish-a-one-page-pricing-model-for-feedback
- https://trello.com/c/bEXUnn9y/225-customers-can-generate-info-about-their-likely-costs-via-the-landing-page

**Comment by mogul** [comment]
For reference, there's a [directory with current materials in the cloud.gov team folder](https://drive.google.com/drive/folders/0Bx6EvBXVDWwhNkhKRXNTcTF6Ymc). See also PR #28 .

**Comment by dlapiduz** [comment]
Here is the pull request starting some of this work: https://github.com/18F/cg-landing/pull/28

**Comment by mogul** [comment]
Can you guys rework the markdown in #28 to reflect the [info we put together for the meeting earlier this week](https://docs.google.com/spreadsheets/d/1uModUuV7AAF2czZDx2rDdWMN2yScgegofPrRqUUI2zg/edit)?

**Comment by mogul** [comment]
This was long since resolved in https://github.com/18F/cg-docs/issues/160
