### ISSUE TITLE
Make it clear who cloud.gov is for

### ISSUE THREAD

**Issue by arowla** [18F/cg-landing#22]
The site doesn't seem to state who the target audience of the service is. This came up in a Hacker News comment on the launch:

https://news.ycombinator.com/item?id=10362544

The site should probably clarify somewhere that it's for federal agencies only.

**Comment by mogul** [comment]
We're doing a follow-up blog post where we'll try to put in that message, and we'll add it to the landing page, too... I think we're almost ready for a FAQ.

**Comment by afeld** [comment]
@arowla There are now a couple pages on the docs site that address this:
- https://docs.cloud.gov/intro/overview/what-is-cloudgov/
- https://docs.cloud.gov/intro/overview/who-can-use-cloudgov/

Feel free to reopen if you don't think they meet the need!

**Comment by arowla** [comment]
LGTM!
