### ISSUE TITLE
set up continuous integration

### ISSUE THREAD

**Issue by afeld** [18F/cg-landing#36]
We want to ensure that new pull requests don't break the site.

**Comment by mogul** [comment]
Wercker is running tests before automatic deploys from `master`... Add anything you want to https://github.com/18F/cg-landing/blob/master/wercker.yml

**Comment by afeld** [comment]
Hmm, same problem as https://github.com/18F/cg-docs/issues/146 I presume... @dlapiduz mind replying to your support email saying we have multiple repositories (probably others I haven't encountered yet) where this is the case?

**Comment by dlapiduz** [comment]
yeah, done
