### ISSUE TITLE
"Deck" in nav bar is confusing

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-landing#64]
The "Deck" link in the nav bar goes to an application called "Cf-Deck" but is hosted at the URL "console.cloud.gov". The repository that powers that application is [18f/cg-deck](/18f/cg-deck).

I think the application name, the menu link text and the URL should all match or be similar enough (`docs.cloud.gov` for "Documentation"), though I think the repo can be called anything as long as there is a description, which [there is](https://github.com/18f/cg-deck#whats-a-deck).

Just a note that this will also require changes be made in the following repositories to make all global navs look similar:
1. [18f/cg-deck](/18f/cg-deck)
2. [18f/cg-docs](/18f/cg-docs)

**Comment by jeremiak** [comment]
Now that we have 18f/cg-deck#296 closed, I wanted to bump this issue. On 18f/cg-deck there is now a link on the far right of the navigation menu for logging in and out of the application. Something similar should be used across the suite of sites using the cloud.gov header.

One option that I thought of after a Slack thread was to use "Dashboard" on the far right of the [cg-landing](/18f/cg-landing) and [cg-docs](/18f/cg-docs) navigation, in place of "Deck". Some people have referred colloquially to the deck as "dashboard" and we even use it as the main URL of the 18f/cg-deck application (https://console-staging.cloud.gov/#/dashboard)

Screenshot of login link on cg-deck:
![Screenshot of login link on cg-deck](https://camo.githubusercontent.com/deff43c0255cc5f06f7332d8d252053112ac5cb3/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f3077336a304a33763057314134323332327730742f53637265656e25323053686f74253230323031362d30352d32372532306174253230352e33392e3534253230504d2e706e673f763d3935313736666664)

Screenshot of proposed text/navigation change:
![Screenshot of proposed text/navigation change](https://s3.amazonaws.com/f.cl.ly/items/1g3s0e0X0x2s3I2a3x25/Screen%20Shot%202016-06-01%20at%2012.28.41%20AM.png?v=f2108e9e)

**Comment by msecret** [comment]
I think this was completed.
