### ISSUE TITLE
Clicking in the "The Government Innovation Platform" section of the page (right below header) causes gray box artifact to show on page

### ISSUE THREAD

**Issue by wslack** [18F/cg-landing#67]
<img width="754" alt="screen shot 2016-06-05 at 1 24 37 pm" src="https://cloud.githubusercontent.com/assets/10016577/15807066/ea0c837a-2b20-11e6-8e7e-a23d9a15abb5.png">

Am running Chrome Version 50.0.2661.102 (64-bit)

**Comment by jonathanhefner** [comment]
Confirming this happens in Chrome 49 (32-bit), but not in Firefox 46.

**Comment by brittag** [comment]
Closed by https://github.com/18F/cg-site/pull/8
