### ISSUE TITLE
switch to using Concourse for deploying in us-east

### ISSUE THREAD

**Issue by afeld** [18F/cg-landing#79]
Follow-up to #74.

Currently the us-east deployment is using Wercker, whereas the govcloud deploy is using Concourse. Let's turn off the Wercker deploy so that it's consistent.

**Comment by jmcarp** [comment]
Here's the pipeline on e/w: https://ci.cloud.gov/pipelines/deploy-landing. Can this be closed @afeld?

**Comment by afeld** [comment]
Went ahead and deleted [the deploy target in Wercker](https://app.wercker.com/#applications/5617233fd77c55dc730d1012/settings/targets).
